-- AlterTable
ALTER TABLE "public"."MaterialInvoice" ALTER COLUMN "deliveryChallanNumber" SET DEFAULT 'NOT PROVIDED',
ALTER COLUMN "vehicleNumber" SET DEFAULT 'NOT PROVIDED',
ALTER COLUMN "vendorContactNumber" SET DEFAULT 'NOT PROVIDED',
ALTER COLUMN "poNumber" SET DEFAULT 'NOT PROVIDED',
ALTER COLUMN "poDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "purposeOfMaterial" SET DEFAULT 'NOT PROVIDED';
